name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read
  checks: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore src

      - name: Build
        run: dotnet build --no-restore src

      - name: Run Tests
        run: dotnet test --no-build src --logger "trx;LogFileName=test_results.trx"

      - name: Publish Test Results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: dotnet tests
          path: src/Shimmering.Analyzers.Tests/TestResults/test_results.trx
          reporter: dotnet-trx

      # Publishing steps only run on push to main, and only on one OS (ubuntu-latest) to avoid duplication
      - name: Pack
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && matrix.os == 'ubuntu-latest'
        run: dotnet pack --output ./artifacts

      - name: Upload NuGet Package
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: ./artifacts/*.nupkg
